#!/usr/bin/env python3
"""
repo-audit-agent
================
An open-source tool powered by Hermes Agent that analyzes GitHub repositories
and generates comprehensive technical audit reports.

Built for the Hermes Agent Challenge 2026.
https://github.com/PropLUG/repo-audit-agent

Author: PropLUG
License: MIT
"""

import subprocess
import sys
import os
import json
import argparse
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

VERSION = "1.0.0"

DEFAULT_OUTPUT_DIR = Path("./reports")

REPORT_SECTIONS = [
    "Executive Summary",
    "Tech Stack",
    "Code Quality Score (X/10)",
    "Risk Register (Top 5 Risks)",
    "Improvement Roadmap (Top 5 Priorities)",
    "Conclusion",
]


# ---------------------------------------------------------------------------
# Hermes Agent Integration
# ---------------------------------------------------------------------------

def build_audit_prompt(repo_url: str, owner: str, repo_name: str) -> str:
    """
    Build the prompt that instructs Hermes Agent to perform the technical audit.

    Hermes Agent uses this prompt to plan its analysis, fetch repository data
    using its built-in web and browser tools, and generate a structured report.

    Args:
        repo_url: Full GitHub repository URL
        owner: Repository owner/organization name
        repo_name: Repository name

    Returns:
        A detailed prompt string for Hermes Agent
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""You are a senior software engineer and technical auditor.

Your task is to analyze the GitHub repository at: {repo_url}

Use your available tools to:
1. Fetch the repository page at {repo_url}
2. Analyze the README, file structure, and codebase
3. Identify the tech stack, code quality indicators, and potential risks

Then generate a complete technical audit report in Markdown format with EXACTLY these sections:

---

# Technical Audit Report: {owner}/{repo_name}

**Generated:** {timestamp}
**Tool:** repo-audit-agent v{VERSION} powered by Hermes Agent
**Repository:** {repo_url}

## Executive Summary

[2-3 paragraphs describing the project purpose, maturity, and overall health]

## Tech Stack

[List all detected languages, frameworks, tools, and infrastructure]

## Code Quality Score

**Score: X/10**

[Justify the score with specific observations about code organization,
documentation, test coverage, and maintainability]

## Risk Register (Top 5)

| # | Risk | Severity | Impact |
|---|------|----------|--------|
| 1 | ... | High/Medium/Low | ... |
| 2 | ... | High/Medium/Low | ... |
| 3 | ... | High/Medium/Low | ... |
| 4 | ... | High/Medium/Low | ... |
| 5 | ... | High/Medium/Low | ... |

[Explain each risk in detail]

## Improvement Roadmap (Top 5)

1. **[Priority name]** — [Specific, actionable improvement with expected impact]
2. **[Priority name]** — [Specific, actionable improvement with expected impact]
3. **[Priority name]** — [Specific, actionable improvement with expected impact]
4. **[Priority name]** — [Specific, actionable improvement with expected impact]
5. **[Priority name]** — [Specific, actionable improvement with expected impact]

## Conclusion

[Final assessment and recommended next steps]

---
*Report generated by repo-audit-agent using Hermes Agent (Nous Research)*

---

Output ONLY the Markdown report above. No additional commentary."""


def run_hermes_audit(repo_url: str, max_turns: int = 15, timeout: int = 300) -> str:
    """
    Invoke Hermes Agent to perform the repository audit.

    Hermes Agent is the core of this tool — it uses its agentic capabilities
    (web browsing, tool use, multi-step reasoning) to fetch and analyze the
    repository, then generates the structured report.

    Args:
        repo_url: GitHub repository URL to analyze
        max_turns: Maximum tool-calling iterations for Hermes Agent
        timeout: Maximum seconds to wait for completion

    Returns:
        The generated audit report as a Markdown string

    Raises:
        subprocess.TimeoutExpired: If Hermes Agent exceeds the timeout
        RuntimeError: If Hermes Agent returns an error
    """
    # Parse owner and repo name from URL
    parts = repo_url.rstrip("/").split("/")
    owner = parts[-2]
    repo_name = parts[-1]

    prompt = build_audit_prompt(repo_url, owner, repo_name)

    print(f"🔍 Analyzing repository: {repo_url}")
    print(f"⏳ Hermes Agent is working (this may take 2-3 minutes)...")
    print("   Hermes will browse the repository, analyze the codebase,")
    print("   and generate a comprehensive technical audit report.\n")

    result = subprocess.run(
        [
            "hermes", "chat",
            "--query", prompt,
            "--quiet",                    # Suppress banners and spinners
            "--max-turns", str(max_turns),
        ],
        capture_output=True,
        text=True,
        timeout=timeout,
    )

    # Combine stdout and stderr for full output
    raw_output = result.stdout + result.stderr

    # Filter out Hermes system messages to get clean Markdown
    clean_lines = [
        line for line in raw_output.split("\n")
        if not line.startswith("session_id:")
        and "tirith security scanner" not in line
        and "rgb:" not in line
        and "^[" not in line
    ]

    report = "\n".join(clean_lines).strip()

    if not report or "API call failed" in report or "Error:" in report:
        raise RuntimeError(
            f"Hermes Agent returned an error:\n{report[:500]}"
        )

    return report


# ---------------------------------------------------------------------------
# Output Handling
# ---------------------------------------------------------------------------

def save_report(report: str, repo_name: str, output_dir: Path) -> Path:
    """
    Save the audit report to a Markdown file.

    Args:
        report: The Markdown report content
        repo_name: Repository name (used in filename)
        output_dir: Directory where reports are saved

    Returns:
        Path to the saved report file
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"audit_{repo_name}_{timestamp}.md"
    filepath = output_dir / filename

    filepath.write_text(report, encoding="utf-8")

    return filepath


def print_summary(report: str, filepath: Path) -> None:
    """Print a summary of the audit results to stdout."""
    lines = report.split("\n")

    print("\n" + "=" * 60)
    print("✅ AUDIT COMPLETE")
    print("=" * 60)

    # Print first 20 lines as preview
    print("\n📄 Report Preview:\n")
    for line in lines[:20]:
        print(line)

    if len(lines) > 20:
        print(f"\n... ({len(lines) - 20} more lines)")

    print(f"\n💾 Full report saved to: {filepath}")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# CLI Interface
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        prog="repo-audit-agent",
        description=(
            "Analyze GitHub repositories and generate technical audit reports "
            "using Hermes Agent."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 audit.py https://github.com/NousResearch/hermes-agent
  python3 audit.py https://github.com/owner/repo --output ./my-reports
  python3 audit.py https://github.com/owner/repo --max-turns 20

Requirements:
  - Hermes Agent installed (https://hermes-agent.org)
  - A valid LLM API key configured in ~/.hermes/.env
        """,
    )

    parser.add_argument(
        "repo_url",
        help="GitHub repository URL to analyze (e.g. https://github.com/owner/repo)",
    )

    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        metavar="DIR",
        help=f"Directory to save reports (default: {DEFAULT_OUTPUT_DIR})",
    )

    parser.add_argument(
        "--max-turns",
        type=int,
        default=15,
        metavar="N",
        help="Maximum Hermes Agent tool-calling iterations (default: 15)",
    )

    parser.add_argument(
        "--timeout",
        type=int,
        default=300,
        metavar="SECONDS",
        help="Maximum seconds to wait for Hermes Agent (default: 300)",
    )

    parser.add_argument(
        "--version", "-v",
        action="version",
        version=f"repo-audit-agent {VERSION}",
    )

    return parser.parse_args()


def validate_repo_url(url: str) -> None:
    """
    Validate that the provided URL is a valid GitHub repository URL.

    Args:
        url: URL to validate

    Raises:
        ValueError: If the URL is not a valid GitHub repository URL
    """
    if not url.startswith("https://github.com/"):
        raise ValueError(
            f"Invalid URL: {url}\n"
            "Please provide a valid GitHub repository URL "
            "(e.g. https://github.com/owner/repo)"
        )

    parts = url.rstrip("/").split("/")
    if len(parts) < 5:
        raise ValueError(
            f"Invalid GitHub URL: {url}\n"
            "URL must include both owner and repository name "
            "(e.g. https://github.com/owner/repo)"
        )


# ---------------------------------------------------------------------------
# Main Entry Point
# ---------------------------------------------------------------------------

def main() -> int:
    """
    Main entry point for repo-audit-agent.

    Returns:
        Exit code (0 = success, 1 = error)
    """
    args = parse_args()

    # Validate input
    try:
        validate_repo_url(args.repo_url)
    except ValueError as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        return 1

    repo_name = args.repo_url.rstrip("/").split("/")[-1]

    # Run the audit using Hermes Agent
    try:
        report = run_hermes_audit(
            repo_url=args.repo_url,
            max_turns=args.max_turns,
            timeout=args.timeout,
        )
    except subprocess.TimeoutExpired:
        print(
            f"❌ Error: Hermes Agent timed out after {args.timeout} seconds.\n"
            "Try increasing --timeout or --max-turns.",
            file=sys.stderr,
        )
        return 1
    except RuntimeError as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        return 1
    except FileNotFoundError:
        print(
            "❌ Error: 'hermes' command not found.\n"
            "Please install Hermes Agent: https://hermes-agent.org",
            file=sys.stderr,
        )
        return 1

    # Save and display results
    filepath = save_report(report, repo_name, args.output)
    print_summary(report, filepath)

    return 0


if __name__ == "__main__":
    sys.exit(main())
